version: '3.3'
services:
  db:
    image: mongo:3.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    restart: always
    secrets:
      - db_password
    volumes:
      - ./db/:/data/db/
secrets:
  db_password:
    file: ./conf/db_password
